/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/iyacontrol/shareit/pkg/apis/confighpa/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeConfigHpas implements ConfigHpaInterface
type FakeConfigHpas struct {
	Fake *FakeConfighpaV1beta1
	ns   string
}

var confighpasResource = schema.GroupVersionResource{Group: "confighpa.shareit.com", Version: "v1beta1", Resource: "confighpas"}

var confighpasKind = schema.GroupVersionKind{Group: "confighpa.shareit.com", Version: "v1beta1", Kind: "ConfigHpa"}

// Get takes name of the configHpa, and returns the corresponding configHpa object, and an error if there is any.
func (c *FakeConfigHpas) Get(name string, options v1.GetOptions) (result *v1beta1.ConfigHpa, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(confighpasResource, c.ns, name), &v1beta1.ConfigHpa{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ConfigHpa), err
}

// List takes label and field selectors, and returns the list of ConfigHpas that match those selectors.
func (c *FakeConfigHpas) List(opts v1.ListOptions) (result *v1beta1.ConfigHpaList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(confighpasResource, confighpasKind, c.ns, opts), &v1beta1.ConfigHpaList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.ConfigHpaList{ListMeta: obj.(*v1beta1.ConfigHpaList).ListMeta}
	for _, item := range obj.(*v1beta1.ConfigHpaList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested configHpas.
func (c *FakeConfigHpas) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(confighpasResource, c.ns, opts))

}

// Create takes the representation of a configHpa and creates it.  Returns the server's representation of the configHpa, and an error, if there is any.
func (c *FakeConfigHpas) Create(configHpa *v1beta1.ConfigHpa) (result *v1beta1.ConfigHpa, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(confighpasResource, c.ns, configHpa), &v1beta1.ConfigHpa{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ConfigHpa), err
}

// Update takes the representation of a configHpa and updates it. Returns the server's representation of the configHpa, and an error, if there is any.
func (c *FakeConfigHpas) Update(configHpa *v1beta1.ConfigHpa) (result *v1beta1.ConfigHpa, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(confighpasResource, c.ns, configHpa), &v1beta1.ConfigHpa{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ConfigHpa), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeConfigHpas) UpdateStatus(configHpa *v1beta1.ConfigHpa) (*v1beta1.ConfigHpa, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(confighpasResource, "status", c.ns, configHpa), &v1beta1.ConfigHpa{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ConfigHpa), err
}

// Delete takes name of the configHpa and deletes it. Returns an error if one occurs.
func (c *FakeConfigHpas) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(confighpasResource, c.ns, name), &v1beta1.ConfigHpa{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeConfigHpas) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(confighpasResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.ConfigHpaList{})
	return err
}

// Patch applies the patch and returns the patched configHpa.
func (c *FakeConfigHpas) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.ConfigHpa, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(confighpasResource, c.ns, name, pt, data, subresources...), &v1beta1.ConfigHpa{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ConfigHpa), err
}
