/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"time"

	v1beta1 "github.com/iyacontrol/shareit/pkg/apis/confighpa/v1beta1"
	scheme "github.com/iyacontrol/shareit/pkg/client/confighpa/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ConfigHpasGetter has a method to return a ConfigHpaInterface.
// A group's client should implement this interface.
type ConfigHpasGetter interface {
	ConfigHpas(namespace string) ConfigHpaInterface
}

// ConfigHpaInterface has methods to work with ConfigHpa resources.
type ConfigHpaInterface interface {
	Create(*v1beta1.ConfigHpa) (*v1beta1.ConfigHpa, error)
	Update(*v1beta1.ConfigHpa) (*v1beta1.ConfigHpa, error)
	UpdateStatus(*v1beta1.ConfigHpa) (*v1beta1.ConfigHpa, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.ConfigHpa, error)
	List(opts v1.ListOptions) (*v1beta1.ConfigHpaList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.ConfigHpa, err error)
	ConfigHpaExpansion
}

// configHpas implements ConfigHpaInterface
type configHpas struct {
	client rest.Interface
	ns     string
}

// newConfigHpas returns a ConfigHpas
func newConfigHpas(c *ConfighpaV1beta1Client, namespace string) *configHpas {
	return &configHpas{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the configHpa, and returns the corresponding configHpa object, and an error if there is any.
func (c *configHpas) Get(name string, options v1.GetOptions) (result *v1beta1.ConfigHpa, err error) {
	result = &v1beta1.ConfigHpa{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("confighpas").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ConfigHpas that match those selectors.
func (c *configHpas) List(opts v1.ListOptions) (result *v1beta1.ConfigHpaList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.ConfigHpaList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("confighpas").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested configHpas.
func (c *configHpas) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("confighpas").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a configHpa and creates it.  Returns the server's representation of the configHpa, and an error, if there is any.
func (c *configHpas) Create(configHpa *v1beta1.ConfigHpa) (result *v1beta1.ConfigHpa, err error) {
	result = &v1beta1.ConfigHpa{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("confighpas").
		Body(configHpa).
		Do().
		Into(result)
	return
}

// Update takes the representation of a configHpa and updates it. Returns the server's representation of the configHpa, and an error, if there is any.
func (c *configHpas) Update(configHpa *v1beta1.ConfigHpa) (result *v1beta1.ConfigHpa, err error) {
	result = &v1beta1.ConfigHpa{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("confighpas").
		Name(configHpa.Name).
		Body(configHpa).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *configHpas) UpdateStatus(configHpa *v1beta1.ConfigHpa) (result *v1beta1.ConfigHpa, err error) {
	result = &v1beta1.ConfigHpa{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("confighpas").
		Name(configHpa.Name).
		SubResource("status").
		Body(configHpa).
		Do().
		Into(result)
	return
}

// Delete takes name of the configHpa and deletes it. Returns an error if one occurs.
func (c *configHpas) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("confighpas").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *configHpas) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("confighpas").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched configHpa.
func (c *configHpas) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.ConfigHpa, err error) {
	result = &v1beta1.ConfigHpa{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("confighpas").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
