/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	time "time"

	confighpav1beta1 "github.com/iyacontrol/shareit/pkg/apis/confighpa/v1beta1"
	versioned "github.com/iyacontrol/shareit/pkg/client/confighpa/clientset/versioned"
	internalinterfaces "github.com/iyacontrol/shareit/pkg/client/confighpa/informers/externalversions/internalinterfaces"
	v1beta1 "github.com/iyacontrol/shareit/pkg/client/confighpa/listers/confighpa/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ConfigHpaInformer provides access to a shared informer and lister for
// ConfigHpas.
type ConfigHpaInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.ConfigHpaLister
}

type configHpaInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewConfigHpaInformer constructs a new informer for ConfigHpa type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewConfigHpaInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredConfigHpaInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredConfigHpaInformer constructs a new informer for ConfigHpa type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredConfigHpaInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ConfighpaV1beta1().ConfigHpas(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ConfighpaV1beta1().ConfigHpas(namespace).Watch(options)
			},
		},
		&confighpav1beta1.ConfigHpa{},
		resyncPeriod,
		indexers,
	)
}

func (f *configHpaInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredConfigHpaInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *configHpaInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&confighpav1beta1.ConfigHpa{}, f.defaultInformer)
}

func (f *configHpaInformer) Lister() v1beta1.ConfigHpaLister {
	return v1beta1.NewConfigHpaLister(f.Informer().GetIndexer())
}
